### ISSUE TITLE
Midnight Shift Issue

### ISSUE THREAD

**Issue by graham609** [AnonymousController/wstc#2]
My facility will publish the midnight shift on the following day and that causes WSTC to put the date on the date of the shift instead of backdating the start of the shift to the previous day. For example..WMT Scheduler will show 11/23/21 as 22M, but the shift actually starts on 11/22/21 yet WSTC will show the shift starting on 11/23/21. Is there a way to fix this so that the midnight shift starts on the day prior and ends on the published date of the schedule?

**Comment by AnonymousController** [comment]
Fixed, two years later...
