### ISSUE TITLE
1600 shift showing wrong day

### ISSUE THREAD

**Issue by wilme861** [AnonymousController/wstc#4]
Anytime my schedule has a 1600-0000 shift, it shows up on the calendar on the previous day. For example, if I have a 1600-0000 shift on a Friday night shift, it shows up in my calendar as a Thursday night 1600-0000 shift instead.

**Comment by AnonymousController** [comment]
I was afraid this would happen. It's a result of fixing the mid-shift logic. My code assumes that any shift with a start time earlier than its end time is a mid shift and should begin on the previous day. 0000 is earlier than 1600, so this shift gets flagged.

For this specific 1600-0000 shift, I will not be changing the logic. You can get around the issue by editing the Shift End time in the Shift Legends plist to 23:59. If I get reports from other facilities that have things like 1800-0200 or 2000-0400 shifts I will have to figure something else out.

The Shift Legends plist can be found at [user home folder] > Library > Application Support > WebScheduleToCalendar > ShiftLegends.plist.
